NAME: Pretrain_Mixed # Experiment names
ACCELERATOR: 'gpu' # Devices optioncal: “cpu”, “gpu”, “tpu”, “ipu”, “hpu”, “mps, “auto”
NUM_NODES: 1 # Number of GPU nodes for distributed training
DEVICE: [0,1,2,3] # Index of gpus eg. [0] or [0,1,2,3,4,5,6,7]

Selected_type: separate_rot  # defaut separate_rot
Representation_type:
  full_h3d:
    ori: beat_smplx_joints
    tar: beat_smplx_full
    vae_test_dim: 263
  full_rot:
    ori: beat_smplx_joints
    tar: beat_smplx_full
    vae_test_dim: 330
  separate_rot:
    face:
      ori: beat_smplx_joints
      tar: beat_smplx_face
      vae_test_dim: 106
    hand:
      ori: beat_smplx_joints
      tar: beat_smplx_hand
      vae_test_dim: 180
    upper:
      ori: beat_smplx_joints
      tar: beat_smplx_upper
      vae_test_dim: 78
    lower:
      ori: beat_smplx_joints
      tar: beat_smplx_lower
      vae_test_dim: 54


TRAIN:
  #---------------------------------
  STAGE: lm_pretrain # stage "vae" , "lm_pretrain", "lm_instruct"
  #---------------------------------
  NUM_WORKERS: 8 # Number of workers
  BATCH_SIZE: 24 # Size of batches  12
  END_EPOCH: 999999 # End epoch
  PRECISION: 'bf16'
  FORCE_BF16: False
  RESUME: '' # Resume training from this path
  PRETRAINED: '' # Preatrained model path
  PRETRAINED_VQ: '/simurgh/u/juze/code/exp_motion/language_of_motion/models/pretrained_vq_exp_ds/vq_ds_paper_version.ckpt' # Preatrained vq model path

  OPTIM:
    target: AdamW
    params:
      lr: 2e-4
      betas: [0.9, 0.99]
      weight_decay: 0.0

# Evaluating Configuration
EVAL:
  BATCH_SIZE: 32 # Evaluating Batch size
  SPLIT: test

TEST:
#  CHECKPOINTS: checkpoints/MotionGPT-base/motiongpt_s3_h3d.tar
  CHECKPOINTS: ''
  SPLIT: test
  BATCH_SIZE: 1 # training Batch size

DATASET:
  vary_length: False
  pose_fps: 30
  unit_length: 4
  pre_frames: 4
  test_length: 120
  audio_fps: 16000
  audio_down: 320
  motion_representation: ${Selected_type} # "rotation" or "h3d"
  target: lom.data.MixedDataset.MixedDataModule
  datasets:
    - name: "BEAT2"
      code_path_audio: "audios_token"
      stride: 20
      training_speakers: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
      testing_speakers: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
      additional_data: True # True or False
      pose_rep: smplxflame_30
      code_path: "TOKENS_DS4"
      instructions_file: "template_instructions_beat2.json"
    - name: "AMASS"
      stride: 20
      max_length: 150     #### Our token length limitation
      min_length: 4
      code_path: "TOKENS_DS4"
      instructions_file: "template_instructions_amass.json"d


METRIC:
  TYPE: ['CoSpeechMetrics']

LOSS:
  LAMBDA_FEATURE: 1.0
  LAMBDA_VELOCITY: 0.5
  LAMBDA_COMMIT: 0.02
  LAMBDA_CLS: 1.0
  ABLATION:
    RECONS_LOSS: 'l1_smooth'

model:
  target: lom.models.lom.Language_Motion
  params:
    # condition: 'audio'
    task: 'a2m'
    lm: ${lm.lom}
    modality_setup:
      params:
        audio_fps: ${DATASET.audio_fps}
        audio_down: ${DATASET.audio_down}  ## since the hubert model is trained on 320hz audio, and we found also have another version of hubert model trained on 640 downsampling setup
        motion_fps: ${DATASET.pose_fps}
        motion_down: ${DATASET.unit_length}
    modality_tokenizer:
      vae_face:
        target: lom.archs.lom_vq.VQVAEConvZeroDSUS_PaperVersion
        params:
          vae_layer: 3
          code_num: 256
          codebook_size: 256
          vae_quantizer_lambda: 1
          vae_test_dim: ${Representation_type.${Selected_type}.face.vae_test_dim}  #dynamic
      vae_hand:
        target: lom.archs.lom_vq.VQVAEConvZeroDSUS_PaperVersion
        params:
          vae_layer: 3
          code_num: 256
          codebook_size: 256
          vae_quantizer_lambda: 1
          vae_test_dim: ${Representation_type.${Selected_type}.hand.vae_test_dim}  #dynamic
      vae_upper:
        target: lom.archs.lom_vq.VQVAEConvZeroDSUS_PaperVersion
        params:
          vae_layer: 3
          code_num: 256
          codebook_size: 256
          vae_quantizer_lambda: 1
          vae_test_dim: ${Representation_type.${Selected_type}.upper.vae_test_dim}  #dynamic
      vae_lower:
        target: lom.archs.lom_vq.VQVAEConvZeroDSUS_PaperVersion
        params:
          vae_layer: 3
          code_num: 256
          codebook_size: 256
          vae_quantizer_lambda: 1
          vae_test_dim: ${Representation_type.${Selected_type}.lower.vae_test_dim}  #dynamic
      vae_global:
        target: lom.archs.lom_vq.VAEConvZero
        params:
          vae_layer: 4
          code_num: 256
          codebook_size: 256
          vae_quantizer_lambda: 1
          vae_test_dim: 61

LOGGER:
  TYPE: ['wandb']
  VAL_EVERY_STEPS: 1
  WANDB:
    params:
      project: language_motion
